freebsd_instance:
  image: freebsd-11-1-release-amd64

task:
  name: stable-x86_64-unknown-freebsd
  env:
    RUST_BACKTRACE: 1
  setup_script:
    - pkg install -y curl
    - curl https://sh.rustup.rs -sSf --output rustup.sh
    - sh rustup.sh -y
  test_script:
    - . $HOME/.cargo/env
    - cargo build --verbose
    - cargo test --no-fail-fast --verbose --all -- --nocapture
