sudo: required
language: rust
rust:
  - stable
#  - beta
#  - nightly
os:
  - windows
  - linux
  - osx

cache: cargo
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
env:
  global:
    - RUST_BACKTRACE=1
script:
  - |
      cargo build --verbose --all
      cargo test --no-fail-fast --verbose --all -- --nocapture
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      export CARGO_TARGET_DIR="$(pwd)/target"
      RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --force --git https://github.com/AnderEnder/tarpaulin --branch stable-master cargo-tarpaulin
      unset CARGO_TARGET_DIR
    fi
after_success:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      cargo tarpaulin --skip-clean -f --out Xml
      bash <(curl -s https://codecov.io/bash)
    fi
before_deploy:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == "stable" && "$TRAVIS_OS_NAME" == "linux" ]]; then
      cargo package
      cargo publish --token $CARGO_TOKEN
    fi
  - cargo build --release
#  - sudo bash -x ci/openssl.sh linux-x86_64 musl- -static
#  - CC_x86_64_unknown_linux_musl=musl-gcc OPENSSL_STATIC=yes OPENSSL_LIB_DIR=/openssl/lib OPENSSL_INCLUDE_DIR=/openssl/include cargo build --release
  - tar -C target/release -czf $(pwd)/s3find-$TRAVIS_TAG-x86_64-$TRAVIS_OS_NAME.tar.gz s3find
deploy:
  api_key:
    secure: "aETdgBzYdHgC2Wxf/IbYlD2YH98I9ZGn6D+CeN67K/UjkidbTnh8BavJjIu9OW50rfXyt5MkTXz0v4bgrcllCgDUFVoDa9RqItr9v8b2S3HTbB3dgdQVrRnbAt8OALMY+xDb2ih50H2i6/nbRmOiOMY0K9icx2miwrlS1Q2emtm7x6q3cOaJl4IqMfOWkvt7fuqbfhiX6QXjbm/SbNlENrwLdRvMbWQQoSIlucDTVDbSSpSJbs9Tnp6N7lYox7CeCJniVBSkUQ78ytKhCVuYCmZlwOowzF2RsunApzPvweAixS4gGCzOkAzMc2jyAzyAma7XFxlgtJHKVyn5OtSJ1/fjTnsAh64RFmllteJnCHrhIAw4HhNIjiszQZQmlvWT2zGZA5yuR/asz8yxQ6z2O/khcHA4PYkFjn2yNg/suYhV8iug71YQscnlBQ2H894wAjIAhvGoNA6DON8aF+Nwu0Qz5bXzJLPjJDpEgm74Jm+Ngw0dUll0Y7SE3EQYrwTwXeveJdyNOI1cu1qWCa4gqeBYk/IevpxR8Mm4EikZiKT3UiZPkOc4VHiliqlKBK5/rxX99UrQmrtMibOzd/DnjwdQEZFMVVZ++cKzf4zKDvBKnew6yWHVAWWeGa8xkzb9xY9MpA0n2cVIqmenxdQ0pj4AJmycZ09ohM7suAly5A0="
  file_glob: true
  file: s3find-$TRAVIS_TAG-x86_64-$TRAVIS_OS_NAME.*
  on:
    condition: "$TRAVIS_RUST_VERSION = stable"
    tags: true
  provider: releases
  skip_cleanup: true
