name: Rust

on:
  push:
    branches:
      - "*"
  pull_request:

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
        if: matrix.os == 'macOS-latest'
      - name: build
        run: cargo build --verbose
      - name: test
        run: cargo test --no-fail-fast --verbose --all -- --nocapture
        env:
          RUST_BACKTRACE: 1
